# Generated by Django 4.2.20 on 2025-03-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdr_manager', '0002_item_remove_charactersheet_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='game_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jdr_manager.gametemplate'),
        ),
    ]
